// swift-tools-version: 5.9
//
// Zhip — root SPM package.
//
// Single flat manifest at repo root. The `Zhip.xcodeproj` (generated by
// XcodeGen) consumes the products from this package; the iOS-app target
// itself is an ultra-tiny shell that just calls into the `AppFeature`
// product's public bootstrap.
//
// Library products:
//
//   Validation                          reactive validation framework
//   Resources                           bundled fonts/html/audio (Bundle.module)
//   AppFeature                          everything else — the Zhip app itself
//                                       (Coordinators, Scenes, Views, ViewModels,
//                                       Models, UseCases, Persistence, ...).
//
// The reactive-MVVM scaffolding (formerly `SingleLineController*`) lives
// in a sibling repo, consumed below as the `NanoViewController` package.

import PackageDescription

let package = Package(
    name: "Zhip",
    // Required by SPM when any target ships localized resources (.xcstrings etc.).
    // The Resources/AppFeature targets host the .xcstrings catalogs.
    defaultLocalization: "en",
    // macOS 13 listed alongside iOS so `swift build` / `swift test` on a
    // macOS host can exercise the Combine APIs. The actual app is iOS-only;
    // the macOS minimum exists only for the package's own host-side runs.
    // iOS 17 matches the Zhip iOS-app target's deployment target in project.yml.
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        // Reactive validation framework.
        .library(name: "Validation", targets: ["Validation"]),
        // Bundled resources (fonts, html, audio) routed through Bundle.module.
        .library(name: "Resources", targets: ["Resources"]),
        // The Zhip app itself, minus the iOS-app shell.
        .library(name: "AppFeature", targets: ["AppFeature"]),
    ],
    dependencies: [
        // Sibling repo containing the reactive-MVVM scaffolding (was the
        // `SingleLineController*` modules — see ../NanoViewController).
        // Local-path dep until NanoViewController gets a tagged release.
        .package(path: "../NanoViewController"),
        // Third-party SPM deps consumed by AppFeature. Versions mirror the
        // Zhip.xcodeproj's previous package references.
        .package(url: "https://github.com/OpenZesame/Zesame", from: "2.0.0"),
        .package(url: "https://github.com/EFPrefix/EFQRCode", from: "6.1.0"),
        .package(url: "https://github.com/Skyscanner/SkyFloatingLabelTextField", from: "4.0.0"),
        .package(url: "https://github.com/roberthein/TinyConstraints", from: "4.0.1"),
        .package(url: "https://github.com/SwiftyBeaver/SwiftyBeaver", from: "1.9.5"),
        .package(url: "https://github.com/yannickl/QRCodeReader.swift", from: "10.1.1"),
        .package(url: "https://github.com/evgenyneu/keychain-swift", from: "19.0.0"),
        .package(url: "https://github.com/hackiftekhar/IQKeyboardManager", from: "6.5.6"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "11.0.0"),
        .package(url: "https://github.com/hmlongco/Factory", from: "2.4.0"),
    ],
    targets: [
        // MARK: - Validation

        .target(
            name: "Validation",
            dependencies: [
                .product(name: "NanoViewControllerCore", package: "NanoViewController"),
                .product(name: "NanoViewControllerCombine", package: "NanoViewController"),
            ]
        ),

        // MARK: - Resources

        .target(
            name: "Resources",
            // Resources/ subdir is implicitly processed by SPM.
            resources: [
                .process("Resources"),
            ]
        ),

        // MARK: - AppFeature

        .target(
            name: "AppFeature",
            dependencies: [
                // NanoViewController stack (sibling repo).
                .product(name: "NanoViewControllerCore", package: "NanoViewController"),
                .product(name: "NanoViewControllerCombine", package: "NanoViewController"),
                .product(name: "NanoViewControllerNavigation", package: "NanoViewController"),
                .product(name: "NanoViewControllerController", package: "NanoViewController"),
                .product(name: "NanoViewControllerSceneViews", package: "NanoViewController"),
                .product(name: "NanoViewControllerDIPrimitives", package: "NanoViewController"),
                "Validation",
                "Resources",
                // Third-party SPM products
                .product(name: "Zesame", package: "Zesame"),
                .product(name: "EFQRCode", package: "EFQRCode"),
                .product(name: "SkyFloatingLabelTextField", package: "SkyFloatingLabelTextField"),
                .product(name: "TinyConstraints", package: "TinyConstraints"),
                .product(name: "SwiftyBeaver", package: "SwiftyBeaver"),
                .product(name: "QRCodeReader", package: "QRCodeReader.swift"),
                .product(name: "KeychainSwift", package: "keychain-swift"),
                .product(name: "IQKeyboardManagerSwift", package: "IQKeyboardManager"),
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk"),
                .product(name: "Factory", package: "Factory"),
            ],
            resources: [
                // .xcstrings catalogs auto-generate `String.LocalizationValue.<Catalog>`
                // symbols scoped to this module.
                .process("Localization"),
                // Asset catalog (Images/Icons) auto-generates `ImageResource.<name>`
                // symbols. AppIcon.appiconset stays in App/Assets.xcassets because
                // ASSETCATALOG_COMPILER_APPICON_NAME on the iOS-app target needs it.
                .process("Resources/Assets.xcassets"),
            ]
        ),

        // MARK: - Test targets

        .testTarget(
            name: "ValidationTests",
            dependencies: ["Validation"]
        ),
    ]
)
