// swift-tools-version: 5.9
//
// Zhip — root SPM package.
//
// Folds the previously-separate `SingleLineController/` and `Validation/`
// packages into a single flat manifest at repo root. The `Zhip.xcodeproj`
// (generated by XcodeGen) consumes the products from this package; the
// app target itself is an ultra-tiny shell that just calls into
// `AppFeature.AppCoordinator.start()`.
//
// Layered SLC products:
//   SingleLineControllerCore           value types only; no UIKit
//   SingleLineControllerCombine        Combine helpers + Binder + --> operator
//   SingleLineControllerNavigation     Coordinator pattern + Navigator
//   SingleLineControllerController     SceneController, BarButton plumbing, nav-bar layout
//   SingleLineControllerSceneViews     AbstractSceneView + SingleCellTypeTableView
//   SingleLineControllerDIPrimitives   protocol-only DI (Clock, MainScheduler, …)
//
// Sibling reactive validation framework:
//   Validation                          AnyValidation, Validation, InputValidator,
//                                       ValidationRule, eagerValidLazyError…
//
// Future plan: re-extract SingleLineController* into a sibling repo. For
// now, flat single-package keeps cross-package wiring simple.

import PackageDescription

let package = Package(
    name: "Zhip",
    // macOS 13 listed alongside iOS so `swift build` / `swift test` on a
    // macOS host can exercise the Combine APIs. The actual app is iOS-only;
    // the macOS minimum exists only for the package's own host-side runs.
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        // SLC product surface (will be re-extracted to a sibling repo later).
        .library(name: "SingleLineControllerCore", targets: ["SingleLineControllerCore"]),
        .library(name: "SingleLineControllerCombine", targets: ["SingleLineControllerCombine"]),
        .library(name: "SingleLineControllerNavigation", targets: ["SingleLineControllerNavigation"]),
        .library(name: "SingleLineControllerController", targets: ["SingleLineControllerController"]),
        .library(name: "SingleLineControllerSceneViews", targets: ["SingleLineControllerSceneViews"]),
        .library(name: "SingleLineControllerDIPrimitives", targets: ["SingleLineControllerDIPrimitives"]),
        // Reactive validation framework.
        .library(name: "Validation", targets: ["Validation"]),
        // Bundled resources (fonts, html, audio) routed through Bundle.module.
        .library(name: "Resources", targets: ["Resources"]),
    ],
    targets: [
        // MARK: - SingleLineController

        .target(name: "SingleLineControllerCore"),
        .target(
            name: "SingleLineControllerCombine",
            dependencies: ["SingleLineControllerCore"]
        ),
        .target(
            name: "SingleLineControllerNavigation",
            dependencies: ["SingleLineControllerCore"]
        ),
        .target(
            name: "SingleLineControllerController",
            dependencies: [
                "SingleLineControllerCore",
                "SingleLineControllerCombine",
                "SingleLineControllerNavigation",
                "SingleLineControllerDIPrimitives",
            ]
        ),
        .target(
            name: "SingleLineControllerSceneViews",
            dependencies: [
                "SingleLineControllerCore",
                "SingleLineControllerCombine",
                "SingleLineControllerController",
            ]
        ),
        .target(name: "SingleLineControllerDIPrimitives"),

        // MARK: - Validation

        .target(
            name: "Validation",
            dependencies: [
                "SingleLineControllerCore",
                "SingleLineControllerCombine",
            ]
        ),

        // MARK: - Resources

        .target(
            name: "Resources",
            // Resources/ subdir is implicitly processed by SPM.
            resources: [
                .process("Resources"),
            ]
        ),

        // MARK: - Test targets

        .testTarget(
            name: "SingleLineControllerCoreTests",
            dependencies: ["SingleLineControllerCore"]
        ),
        .testTarget(
            name: "SingleLineControllerCombineTests",
            dependencies: ["SingleLineControllerCombine"]
        ),
        .testTarget(
            name: "ValidationTests",
            dependencies: ["Validation"]
        ),
    ]
)
